allowBuilds:
  esbuild: true
  postinstall-postinstall: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@tootallnate/once@3.0.1'
  - postcss@8.5.10
overrides:
  "@tootallnate/once": ^3.0.1
  '@tootallnate/once@<3.0.1': ^3.0.1
  postcss: ^8.5.10
  postcss@<8.5.10: ^8.5.10
