apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: stock-verify
type: Opaque
stringData:
  mongodb-url: "<MONGO_URL>"
  jwt-secret: "<JWT_SECRET>"
  jwt-refresh-secret: "<JWT_REFRESH_SECRET>"
  redis-url: "<REDIS_URL>"
